<?php
/*
* Implements hook_theme();
*/
use Drupal\Core\Routing\RouteMatchInterface;

function parasol_theme($existing,$type,$theme,$path) {

  $variables =
  ['parsol'=> [
    'variables' => [
      'source_text' => NULL,
     ],
     'template' => 'parasol'
    ]
  ];

  return $variables;
}

function template_preprocess_parasol(&$variables) {

  $marks = ['. ', '! ', '? ', ' . . . ', ': ', '; '];

  for ($i = 0; $i < count($variables['source_text']); $i++) {

    $phrase_arr = explode('. ', $variables['source_text'][$i]);

    for($j = 0; $j < count($phrase_arr)-1; $j++) {
      $phrase_arr[$i] .= $marks[floor(mt_rand(0, count($marks)-1))];
    }
  }

  $variables['source_text'[$i]] = implode('',$phrase_arr);
}

?>
