parasol.settings:
  type: config_object
  label: "Parasol Birds Chirp"
  mapping:
    parasol:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'Monologue.'
        source_text:
          type: text
          label: 'Brids Chirp. Birds Chirp. Birds Chirp. Birds Chirp.'

parasol.syllablemill:
  type: config_object
  label: "Parasol Syllablemill"
  mapping:
    parasol:
      type: mapping
      mapping:
        syllables_qty:
          type: text
          label: 'syllables'
        syllables_cap:
          type: text
          label: 'max syllables'
        words_cap:
          type: text
          label: 'max words'
        phrases_cap:
          type: text
          label: 'max phrases'
        paragraphs_qty:
          type: text
          label: 'paragraphs'

parasol.settings.monologue_block:
  type: block_settings
  label: 'Monologue Block'
  mapping:
    type: text
    label: 'Monologue Block Settings'
