parasol.settings:
  type: config_object
  label: "Parasol Birds Chirp"
  mapping:
    parasol:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'Monologue.'
        source_text:
          type: text
          label: 'Brids Chirp.'
parasol.settings.monologue_block:
  type: block_settings
  label: 'Monologue Block'
  mapping:
    type: text
    label: 'Monologue Block Settings'
